#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Check written by Craig Cook  1 April 2015
# - version 1
# - version 1.1  Added factory_settings, changed params

# Example output from agent:
#<<<redis_queue>>>
#some-queue-name1 0
#some-queue-name2 0
#some-queue-name3 0

factory_settings["redis_queue_default_levels"] = {
    "warn_size" : ( None ),
    "crit_size" : ( None ),
}

def inventory_redis_queue(info):
    inventory = []
    for line in info:
       # line[0] is the name of the queue
       inventory.append( (line[0], {}) )
    return inventory

def check_redis_queue(item, params, info):

    for line in info:

        queueName = line[0]

        if queueName == item:

            queueLength = int(line[1])
            # Allow for a warn threshold but not require a critical threshold
            warn = params['warn_size']
            crit = params['crit_size']

            if crit is not None and queueLength >= crit:
                state = 2
            elif warn is not None and queueLength >= warn:
                state = 1
            else:
                state = 0

            if state > 0:
                perfdata = [ ('redis_queue', queueLength, warn, crit) ]
            else:
                perfdata = [ ('redis_queue', queueLength) ]

            infotext =  "Queue Length is %d " % queueLength
            infotext += "(Levels Warn/Crit at %s/%s), " % (warn, crit)

            return (state, infotext, perfdata)
    return 2, "Queue not found"

check_info['redis_queue'] = {
    'check_function'          : check_redis_queue,
    'inventory_function'      : inventory_redis_queue,
    "default_levels_variable" : "redis_queue_default_levels",
    'service_description'     : 'REDIS Queue %s',
    'has_perfdata'            : True,
    'group'                   : 'redis_queue',
}
